### ISSUE TITLE
Rank colors over players head isnt' working.

### ISSUE THREAD

**Issue by BobbyTowers** [PurePlugins/PureChat#13]
The color for the ranks over the players head is not working with v1.2.9 and v1.2.8 They work fine with v1.2.7 Chat works fine on all three.

**Comment by JoahDave** [comment]
I <i>have</i> noticed the lack of color...

**Comment by BobbyTowers** [comment]
Still ain't working and I made sure that I had no other plugins installed. I only had PurePerms and PureChat  installed; PM#1258

**Comment by 64FF00** [comment]
@BobbyTowers May I take a look at your groups.yml?

**Comment by BobbyTowers** [comment]
I put it on PocketMine
