### ISSUE TITLE
Can you please fix this problem

### ISSUE THREAD

**Issue by SoyPro** [PurePlugins/PureChat#15]
Why dont you fix the nametag bug i added CoOwner to the groups and i put the permission pchat.colored.then i enter in the game.then i deop me and i talk and the CoOwner doesnt have the color in the rank.this problem have here un purechat 4 months ago.you dont fix this.so fix this or i have to unistall your plugin.dont put me invalid,duplicated.fix and thanks!

**Comment by 64FF00** [comment]
@SoyPro Can you check if it still happens in the latest version?

**Comment by SoyPro** [comment]
Yes i check and still happen.and when i add a group the color doesnt work make and update pls -.-.thks plugin dont work property because you dont update.update it and fix al bugs

**Comment by 64FF00** [comment]
@SoyPro Still not working? https://github.com/PurePlugins/PureChat/releases/tag/v1.3.0

**Comment by SoyPro** [comment]
Thanks very much 64FF00.Great plugins and good job.thanks! For fix the bug!

**Comment by 64FF00** [comment]
@SoyPro <3
