### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by SoyPro** [PurePlugins/PureChat#17]
All its ok but when a player left the game and enter again and talk in the chat appear this "{COLOR_DARK_BLUE}{FORMAT_BOLD}[CoOwner]{COLOR_WHITE}{FORMAT_RESET} {display_name} {COLOR_WHITE}> {message}" but when a player left the game and enter again and talk its appear in the chat of game! Can you fix this bug and when i put the permission phat.colores.chat.its crash my server!fix this,pls!

**Comment by Pub4Game** [comment]
Yes, I have this error too!

**Comment by 64FF00** [comment]
@SoyPro Could you please post your PureChat config.yml and PurePerms groups.yml?

**Comment by SoyPro** [comment]
CoOwner:
    default-chat: "{COLOR_DARK_BLUE}{FORMAT_BOLD}[CoOwner]{FORMAT_RESET}{COLOR_WHITE} {display_name} {COLOR_WHITE}> {message}"
    default-nametag: "{COLOR_DARK_BLUE}{FORMAT_BOLD}[CoOwner]{COLOR_WHITE}{FORMAT_RESET} {display_name}"
    worlds: []
  Mod:
    default-chat: "{COLOR_GOLD}{FORMAT_BOLD}[Mod]{FORMAT_RESET}{COLOR_WHITE} {display_name} {COLOR_WHITE}> {message}"
    default-nametag: "{COLOR_GOLD}{FORMAT_BOLD}[Mod]{COLOR_WHITE}{FORMAT_RESET} {display_name}"
    worlds: []
  Builder:
    default-chat: "{COLOR_AQUA}{FORMAT_BOLD}[Builder]{FORMAT_RESET}{COLOR_WHITE} {display_name} {COLOR_WHITE}> {message}"
    default-nametag: "{COLOR_AQUA}{FORMAT_BOLD}[Builder]{COLOR_WHITE}{FORMAT_RESET} {display_name}"
    worlds: []
  Helper:
    default-chat: "{COLOR_BLUE}{FORMAT_BOLD}[Helper]{FORMAT_RESET}{COLOR_WHITE} {display_name} {COLOR_WHITE}> {message}"
    default-nametag: "{COLOR_BLUE}{FORMAT_BOLD}[Helper]{COLOR_WHITE}{FORMAT_RESET} {display_name}"
    worlds: []
  Member:
    default-chat: "{COLOR_DARK_GRAY}{FORMAT_BOLD}[Member]{FORMAT_RESET}{COLOR_WHITE} {display_name} {COLOR_WHITE}> {message}"
    default-nametag: "{COLOR_GRAY}{FORMAT_BOLD}[Member]{COLOR_WHITE}{FORMAT_RESET} {display_name}"
    worlds: []

**Comment by SoyPro** [comment]
# PurePerms by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

---
# Set default data provider for PurePerms
# - yaml, sqlite3, mysql // NOT FINISHED YET
data-provider: yaml

# Set the default language for PurePerms
# - en, ko, jp, ru, it, sp
# English message resource by @64FF00 and @Samueljh1 (GitHub)
# Korean message resource by @64FF00 (GitHub)
# 제 블로그 이외에 허락없이 마음대로 플러그인 배포하실 시에는 바로 한국어 파일 삭제 조치하고 공유 중단합니다
# Japanese message resource by @onebone (<3) and @haniokasai (GitHub)
# Russian message resource by @vvzar and @Pub4Game (GitHub)
# Italian message resource by @AryToNeX (GitHub)
# Spanish message resource by @iksaku (<3) and @JoahDave (Github)
default-language: en

# Setting this option will allow you to use per-world permissions
# - true / false
enable-multiworld-perms: false

# // NOT FINISHED YET
# MySQL Settings (Only configure this if you are going to use MySQL data provider)
#mysql-settings:
  # Thank you for 100k downloads btw... Love you all <3 #64FF00
  #host: "PurePerms-FTW.loveyou.all"
  #port: 3306
  #user: "YourUsernameGoesHere"
  #password: "YourPasswordGoesHere"
  #db: "YourDBNameGoesHere"
...

**Comment by SoyPro** [comment]
---
Guest:
  isDefault: true
  inheritance: []
  permissions:
  - -essentials.kit
  - -essentials.kit.other
  - -pocketmine.command.me
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.command.list
  - pperms.command.ppinfo
  worlds: []
Admin:
  inheritance:
  - Guest
  permissions:
    3: pocketmine.command.give
    4: pocketmine.command.kick
    5: pocketmine.command.teleport
    8: phat.colored.format
    9: phat.colored.nametag
    10: essentials.god
    11: essentials.fly
    12: essentials.tphere
    13: essentials.suicide
    14: essentials.realname
    15: essentials.repair
    16: essentials.itemdb
    17: essentials.sign.use.warp
    18: essentials.warps.*
    19: morecommands.gmc
    20: morecommands.gms
    21: morecommands.heal
    22: essentials.kill
    23: morecommands.freeze
    24: morecommands.unfreeze
  worlds: []
Owner:
  inheritance:
  - Guest
  - Admin
  permissions:
  - essentials
  - pocketmine.command
  - pperms.command
  worlds: []
OP:
  inheritance: []
  permissions:
  - '*'
  worlds: []
CoOwner:
  isDefault: false
  inheritance: []
  permissions:
  - phat.colored.format
  - phat.colored.nametag
  worlds: []
Mod:
  isDefault: false
  inheritance: []
  permissions:
  - phat.colored.format
  - phat.colored.nametag
  worlds: []
Builder:
  isDefault: false
  inheritance: []
  permissions: []
  worlds: []
Helper:
  isDefault: false
  inheritance: []
  permissions: []
  worlds: []
Member:
  isDefault: false
  inheritance: []
  permissions: []
  worlds: []
...

**Comment by 64FF00** [comment]
It's pchat.colored, not phat.colored

**Comment by SoyPro** [comment]
I have to put phat.colored?or not help me i want to open my server!

**Comment by SoyPro** [comment]
Yes thanks!i like your plugins.thanks!@64FF00!
