### ISSUE TITLE
Non-OP Players have no colored chat

### ISSUE THREAD

**Issue by NexoCube** [PurePlugins/PureChat#18]
I gave YT Rank on my friends and he haven't colored chat but he have colored nametag, but when i gave him OP he got the both colored. 

Sorry for my bad english, i am French

**Comment by NexoCube** [comment]
When i say colored chat i mean when he send a message on the game chat he haven't his colored Rank it's white

**Comment by 64FF00** [comment]
Try adding pchat.colored.format node to the default group

**Comment by NexoCube** [comment]
How that ? I add it to permissions ?

**Comment by NexoCube** [comment]
Thanks you, i just don't understanding that node was permissions nodes x) 

Thanks you, you're a great dev !

**Comment by 64FF00** [comment]
@NexoCube <3
