### ISSUE TITLE
Name Tag Looks Like "[{COLOR_GRAY}Prisoner{COLOR_WHITE}]{FORMAT_RESET} (playername).

### ISSUE THREAD

**Issue by Jefferson629** [PurePlugins/PureChat#19]
Nametag Looks Like "[{COLOR_GRAY}Prisoner{COLOR_WHITE}]{FORMAT_RESET}" IDK Why This Happens..

**Comment by 64FF00** [comment]
@Jefferson629 In PureChat v1.3.0 config.yml...
```YAML
# You might also need to set 'pchat.colored.format' and 'pchat.colored.nametag' to players if you want to allow them to use colored chat and nametags
# Use 'pchat.colored.chat' node to allow color codes for players in chat
```

**Comment by DevBrad** [comment]
I belive that's the issue. The permission isn't a 100% success rate

**Comment by DevBrad** [comment]
So therefore, even though the player has the perm, it doesn't work

**Comment by Jefferson629** [comment]
No It Is Not Invalid @64FF00 Even If The Player Have The Permission Still Doesn't And @DevBrad You're Totally Right Bro.

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PureChat/issues/13
