### ISSUE TITLE
Name Tag

### ISSUE THREAD

**Issue by SahrulGamerz** [PurePlugins/PureChat#25]
Hello,
I have a problem with nametag..when i start the server it load ok..
after i join the server..i see my friend nametag it show like this.
{COLOR_LIGHT_PURPLE}{FORMAT_BOLD}[Premium]{COLOR_WHITE}{FORMAT_RESET} {display_name}

what should i do..

here is my purechat config..

# PureChat by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

---
# Allows you to use per-world chat formats + per-world nametags
# - true / false
enable-multiworld-support: false

# This message will be shown replacing th {faction} tag when a player is not in any faction
# - STRING
custom-no-fac-message: "..."

# A list of all PurePerms groups
groups:
  Newbie:
    # Default tags: {world_name}, {display_name}, {user_name}, {message}
    # Also remember that you can also use {faction} tag if you have FactionsPro plugin installed!
    
    # New feature added in v1.2.4 - Colors!
    # RED: {COLOR_RED}, GREEN: {COLOR_GREEN}, BLUE: {COLOR_BLUE}, LIGHT_PURPLE: {COLOR_LIGHT_PURPLE}, and so on...
    # BOLD: {FORMAT_BOLD}, STRIKETHROUGH: {FORMAT_STRIKETHROUGH}, UNDERLINE: {FORMAT_UNDERLINE}, ITALIC: {FORMAT_ITALIC}
    # RESET: {FORMAT_RESET}
    
    # You might also need to set 'pchat.colored.format' and 'pchat.colored.nametag' to players if you want to allow them to use colored chat and nametags
    # Use 'pchat.colored.chat' node to allow color codes for players in chat
    default-chat: "{COLOR_YELLOW}{FORMAT_BOLD}[Newbie]{COLOR_WHITE}{FORMAT_RESET} {display_name} {COLOR_GRAY}> {message}"
    
    # Almost all of the tags can be applied to nametag formats except {message} tag
    default-nametag: "{COLOR_YELLOW}{FORMAT_BOLD}[Newbie]{COLOR_WHITE}{FORMAT_RESET} {display_name}"
    worlds: []
  VIP:
    default-chat: "{COLOR_GOLD}{FORMAT_BOLD}[VIP]{COLOR_WHITE}{FORMAT_RESET} {display_name} {COLOR_GRAY}> {message}"
    default-nametag: "{COLOR_GOLD}{FORMAT_BOLD}[VIP]{COLOR_WHITE}{FORMAT_RESET} {display_name}"
    worlds: []
  Premium:
    default-chat: "{COLOR_LIGHT_PURPLE}{FORMAT_BOLD}[Premium]{COLOR_WHITE}{FORMAT_RESET} {display_name} {COLOR_GRAY}> {message}"
    default-nametag: "{COLOR_LIGHT_PURPLE}{FORMAT_BOLD}[Premium]{COLOR_WHITE}{FORMAT_RESET} {display_name}"
    worlds: []
  Admin:
    default-chat: "{COLOR_AQUA}{FORMAT_BOLD}[Admin]{COLOR_WHITE}{FORMAT_RESET} {display_name} {COLOR_GRAY}> {message}"
    default-nametag: "{COLOR_AQUA}{FORMAT_BOLD}[Admin]{COLOR_WHITE}{FORMAT_RESET} {display_name}"
    worlds: []
  Owner: 
    default-chat: "{COLOR_RED}{FORMAT_BOLD}[Owner]{COLOR_WHITE}{FORMAT_RESET} {display_name} {COLOR_GRAY}> {message}"
    default-nametag: "{COLOR_RED}{FORMAT_BOLD}[Owner]{COLOR_WHITE}{FORMAT_RESET} {display_name}"
    worlds: []
  OP: 
    default-chat: "{COLOR_GREEN}{FORMAT_BOLD}[OP]{COLOR_WHITE}{FORMAT_RESET} {display_name} {COLOR_GRAY}> {message}"
    default-nametag: "{COLOR_GREEN}{FORMAT_BOLD}[OP]{COLOR_WHITE}{FORMAT_RESET} {display_name}"
    worlds: []

Here also my pureperms group.yml
---
Newbie:
  isDefault: true
  inheritance: []
  permissions:
  - advancedkits.pvp
  - advancedkits.starter
  - essentials.kit
  - essentials.kit.other
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.command.list
  - pocketmine.command.me
  - pperms.command.ppinfo
  worlds: []
VIP:
  inheritance:
  - Newbie
  permissions:
  - advancedkits.pvp
  - advancedkits.starter
  - advancedkits.vip
  - essentials.kit
  - essentials.kit.other
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.command.list
  - pocketmine.command.me
  - pocketmine.command.teleport
  - pocketmine.command.time
  - pperms.command.ppinfo
  worlds: []
Premium:
  inheritance:
  - Newbie
  - VIP
  permissions:
  - advancedkits.premium
  - advancedkits.pvp
  - advancedkits.starter
  - advancedkits.vip
  - essentials.gamemode
  - essentials.kit
  - essentials.kit.other
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.command.gamemode
  - pocketmine.command.list
  - pocketmine.command.me
  - pocketmine.command.teleport
  - pocketmine.command.time
  - pperms.command.ppinfo
  worlds: []
Admin:
  inheritance:
  - Newbie
  - VIP
  - Premium
  permissions:
  - advancedkits.premium
  - advancedkits.pvp
  - advancedkits.starter
  - advancedkits.vip
  - essentials.gamemode
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.broadcast
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.kick
  - pocketmine.command.teleport
  - pocketmine.command.time
  worlds: []
Owner:
  inheritance:
  - Newbie
  - VIP
  - Premium
  - Admin
  permissions:
  - advancedkits.premium
  - advancedkits.pvp
  - advancedkits.starter
  - advancedkits.vip
  - essentials
   - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.command
  - pperms.command
  worlds: []
OP:
  inheritance: []
  permissions:
  - '*'
  worlds: []

Hope You Can Find What Is The Problem..

Thank You

**Comment by Pub4Game** [comment]
Use new version plugin https://github.com/PurePlugins/PureChat/releases/tag/v1.3.3

**Comment by SahrulGamerz** [comment]
ok..after i update it..it crash my server when i join..

Fatal error: Call to undefined method _64FF00\PurePerms\PurePerms::getUserDataMgr() in phar://C:/Users/Acer/Desktop/PocketMine-MP/plugins/PureChat_v1.3.3.phar/src/_64FF00/PureChat/PureChat.php on line 159

Call Stack:
    0.0780     433288   1. {main}() C:\Users\Acer\Desktop\PocketMine-MP\0.12.1.phar:0
    0.0870     428136   2. require('phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/PocketMine.php') C:\Users\Acer\Desktop\PocketMine-MP\0.12.1.phar:1
    0.7530     568160   3. pocketmine\Server->__construct() phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/PocketMine.php:464
   29.4907   17968040   4. pocketmine\Server->start() phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/Server__32bit.php:1701
   29.5487   17983832   5. pocketmine\Server->tickProcessor() phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/Server__32bit.php:2100
   49.5198   26153344   6. pocketmine\Server->tick() phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/Server__32bit.php:2222
   49.5588   26489152   7. pocketmine\Player->checkNetwork() phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/Server__32bit.php:2485
   49.5588   26489152   8. pocketmine\Player->sendNextChunk() phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/Player__32bit.php:1561
   49.6118   27009872   9. pocketmine\Player->doFirstSpawn() phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/Player__32bit.php:720
   49.8289   27019544  10. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/Player__32bit.php:760
   53.0200   27313224  11. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/plugin/PluginManager.php:673
   53.0200   27313224  12. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/plugin/RegisteredListener.php:96
   53.0200   27313304  13. _64FF00\PureChat\ChatListener->onPlayerJoin() phar://C:/Users/Acer/Desktop/PocketMine-MP/0.12.1.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
   53.0210   27313624  14. _64FF00\PureChat\PureChat->getNameTag() phar://C:/Users/Acer/Desktop/PocketMine-MP/plugins/PureChat_v1.3.3.phar/src/_64FF00/PureChat/ChatListener.php:86

**Comment by Pub4Game** [comment]
Update PurePerms https://github.com/PurePlugins/PurePerms/releases/tag/v1.2.2

**Comment by SahrulGamerz** [comment]
yes..thank you very very much... for helping me..

it works now!!

**Comment by SahrulGamerz** [comment]
gonna close this thread
