### ISSUE TITLE
Nametags above heads are not formatted!

### ISSUE THREAD

**Issue by iWoof03** [PurePlugins/PureChat#30]
Hi, I am now running 0.13.0 and noticed a bug where the nametag above people's heads are not colored where they should be. (the chat works fine) I also noted that if you re-apply /setgroup name group, everybody who is on during the time that command is run will start seeing the nametag in color, bold etc. until they/the player leave. Please fix ASAP!

Thanks- Will

**Comment by 64FF00** [comment]
@iWoof03 What version of PureChat are you using now

**Comment by iWoof03** [comment]
I'm running version 1.3.3

**Comment by NML32** [comment]
@iWoof03 I can confirm I'm having the same issue as you.

**Comment by 64FF00** [comment]
Will be fixed in v1.4.0
