### ISSUE TITLE
INFO Fatal error: Call to undefined method _64FF00\PurePerms\PurePerms::getUser() in 

### ISSUE THREAD

**Issue by RocoWayne** [PurePlugins/PureChat#32]
26.01 08:03:35 [Server] Server thread/EMERGENCY Please upload the "/CrashDump_Tue_Jan_26-07.03.35-AKST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
26.01 08:03:35 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
26.01 08:03:35 [Server] INFO Fatal error: Call to undefined method _64FF00\PurePerms\PurePerms::getUser() in phar:///plugins/PureChat_v1.3.0.phar/src/_64FF00/PureChat/PureChat.php on line 159

**Comment by 64FF00** [comment]
@RocoWayne Will be fixed in v1.3.4 :)
