### ISSUE TITLE
API for setting nametags?

### ISSUE THREAD

**Issue by legoboy0215** [PurePlugins/PureChat#36]
For example, my plugin wants to modify a player's nametag, so 
```php
//Troll is an Admin with this tag: [Admin] Troll

$purechat->setNameTag($p, 'Troll'); //Now he is a troll!

//Revert

$purechat->revertToOriginal($p); //Now, his tag is [Admin] Troll again :)
```
I hope you can achieve this!

**Comment by legoboy0215** [comment]
Wait. I think I got it.

**Comment by legoboy0215** [comment]
$player->setDisplayName($purechat->getNameTag($player));

**Comment by 64FF00** [comment]
Added to https://github.com/PurePlugins/PureChat/issues/16
