### ISSUE TITLE
Bug in v1.3.4-BETA-01

### ISSUE THREAD

**Issue by SoyPro** [PurePlugins/PureChat#38]
[Server] [04:10:56] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'PureChat v1.3.4-BETA-01': Undefined index: IsDefault on _64FF00\PureChat\ChatListener

**Comment by 64FF00** [comment]
@SoyPro Please reopen this issue again with the latest PureChat on GitHub

**Comment by SoyPro** [comment]
Ok @_64FF00
