### ISSUE TITLE
Uncaught ReferenceError: _WidgetJPCB0 is not defined 

### ISSUE THREAD

**Issue by Rhai08** [PurePlugins/PureChat#57]
Hi.

I have already tried everything I can do to find what causes this error but I just cannot answers. Has any body experience this?

_WidgetJPCB0?_=_:1 Uncaught ReferenceError: _WidgetJPCB0 is not defined
    at _WidgetJPCB0?_=_:1

What am I missing?

**Comment by Borduni** [comment]
I think you are not at the right repo
