### ISSUE TITLE
Visitor Information Unable to set

### ISSUE THREAD

**Issue by saikrishnareddythummala** [PurePlugins/PureChat#60]
In the visitor information, Except the question no other fields are working.(Name and email id etc..), Please give me the solution ASAP.

<script> 

// values - string 
purechatApi.on('chatbox:ready', function () { 
     purechatApi.set('visitor.name', 'Joe'); // Sets the visitor name to "Joe" 
     purechatApi.set('visitor.email', 'joe@joesmarket.com'); // Sets the visitor's email address to "joe@joesmarket.com" 
     purechatApi.set('visitor.phoneNumber', '6025551234'); // Sets the visitor's phone number "6025551234" 
     purechatApi.set('visitor.question', 'I need some help with an order I have already made'); // Sets the visitor's question to "I need some help with an order I have already made" 
}); 
</script>

(https://www.purechat.com/javascript-api#region=visitor-information)

**Comment by SleepSpace9** [comment]
I think this repository has nothing to do with the product you mentioned. Better you close your issue and contact the right people (probably https://www.purechat.com/support).

**Comment by RocoWayne** [comment]
its another purechat

**Comment by Borduni** [comment]
//CLOSED
