### ISSUE TITLE
How do I activate factions support?

### ISSUE THREAD

**Issue by Dragonblitz10** [PurePlugins/PureChat#62]
Show config and how

**Comment by Borduni** [comment]
You need to set the plugin here:
`
# Set default factions plugin for PureChat
# - FactionsPro / XeviousPE-Factions (§l§9-§8]§b>§7[§cXevious§aTestSrv§7]§b<§8[§9-) / null
default-factions-plugin: ~`

**Comment by kenygamer** [comment]
@Dragonblitz10
`default-factions-plugin: ~`
Change "~" to "FactionsPro"
Without the quotes, of course.

**Comment by Borduni** [comment]
//closed due its not a bug
