### ISSUE TITLE
Crashes client on join

### ISSUE THREAD

**Issue by alexbgameson** [PurePlugins/PureChat#63]
With the latest release of mcpe server software this plugin causes the clients game to crash when they attempt to join.

**Comment by kenygamer** [comment]
@alexbgameson Are you using latest version of PureChat ?

**Comment by kenygamer** [comment]
@LolNova Using tesseract ?

**Comment by Borduni** [comment]
Can u show us your crashlogs/logs?

**Comment by zKoz210** [comment]
Fixed https://github.com/PurePlugins/PurePerms/commit/3b4e4cbbb11690a9aca9979d3e9f3e6c44074d0b, close
