### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by LolNova** [PurePlugins/PureChat#64]
When I add pure chat and pure perms to my server and reload it when I try to join it crashes the same as My friend. When I remove it server works perfectly fine. FIX PLEASE

**Comment by jasonwynn10** [comment]
This is the most unhelpful issue post ever. Update your post when you have more helpful information.

**Comment by Borduni** [comment]
Please send us ur Crash logs/configs. Without any information, we cannot help you

**Comment by Borduni** [comment]
//closed due not enough information
