### ISSUE TITLE
Server thread/CRITICAL]: [PureChat] Invalid nametag found in config.yml (Group: Founder) / Setting it to default value.

### ISSUE THREAD

**Issue by teracube** [PurePlugins/PureChat#67]
Hi,
please find an error 
Server thread/CRITICAL]: [PureChat] Invalid nametag found in config.yml (Group: Founder) / Setting it to default value.
[PureChat] Invalid chat format found in config.yml (Group: Founder) / Setting it to default value.

problem on my config.yml  or issue ?
thanks

PocketMine-MP_1.6.2dev-378
PureChat : https://poggit.pmmp.io/r/9396/PureChat.phar

**Comment by jasonwynn10** [comment]
`Invalid nametag found`
Set the name tag correctly and you won't have the issue
