### ISSUE TITLE
what factions plugin runs good with this

### ISSUE THREAD

**Issue by moneymill2400** [PurePlugins/PureChat#69]

**Comment by jasonwynn10** [comment]
FactionsPro is the only supported one

**Comment by moneymill2400** [comment]
it doesnt work fo me can you send me the latest factionspro that works

**Comment by moneymill2400** [comment]
i dont know how to get it to work

**Comment by jasonwynn10** [comment]
https://poggit.pmmp.io/p/FactionsPro/1.3.11-5
