### ISSUE TITLE
Normal users with pchat.colored permission can't color their messages

### ISSUE THREAD

**Issue by AryToNeX** [PurePlugins/PureChat#7]
When a normal user want to color his message he can't. OPs can color their messages.

**Comment by 64FF00** [comment]
@AryToNeX Could you post your groups.yml here

**Comment by AryToNeX** [comment]
---
User:
  isDefault: true
  inheritance: []
  permissions:
  - -pocketmine.command.me
  - afk
  - f.command
  - massiveeconomy.command.help
  - massiveeconomy.command.money
  - massiveeconomy.command.pay
  - massiveeconomy.receivedefault
  - mcg76.blockhunt
  - mcg76.plugin.tntrun
  - mspawns.hub
  - mspawns.spawn
  - pchat.colored
  - planb.command.planb
  - pocketguard.command.pg
  - pocketmine.command.list
  - sign
  - sign.command
  - simpleauth.command.login
  - simpleauth.command.register
  - simpleauth.lastip
  - simpleauthhelper.command.chpwd
  - simplehome.home
  - simplehome.sethome
  - simplewarp.command.list
  - simplewarp.command.warp
  - wp.motd
  worlds: []
YouTuber:
  inheritance:
  - User
  permissions: []
  worlds: []
VIP:
  inheritance:
  - Utente
  - YouTuber
  permissions:
  - simpleauth.lastip
  worlds: []
Mod:
  inheritance:
  - User
  - VIP
  - YouTuber
  permissions:
  - pocketmine.command.ban
  - pocketmine.command.kick
  - pocketmine.command.teleport
  - pocketmine.command.unban
  - simpleauth.lastip
  - vanish
  worlds: []
Pluginner:
  inheritance:
  - User
  - VIP
  - Mod
  - YouTuber
  permissions:
  - pocketmine.command.plugins
  - simpleauth.lastip
  worlds: []
Builder:
  inheritance:
  - User
  - VIP
  - Mod
  - YouTuber
  permissions:
  - iprotector
  - iprotector.access
  - iprotector.area
  - iprotector.area.create
  - iprotector.area.delete
  - iprotector.area.flag
  - iprotector.area.list
  - iprotector.area.pos1
  - iprotector.area.pos2
  - iprotector.command
  - pocketmine.command.gamemode
  - simpleauth.lastip
  - wp.cmd.gm.exempt
  - wp.cmd.protect.auth
  worlds: []
Admin:
  inheritance:
  - User
  - VIP
  - Mod
  - Builder
  - Pluginner
  - YouTuber
  permissions:
  - broadcaster.info
  - broadcaster.reload
  - broadcaster.sendmessage
  - broadcaster.sendpopup
  - iprotector
  - iprotector.access
  - iprotector.area
  - iprotector.area.create
  - iprotector.area.delete
  - iprotector.area.flag
  - iprotector.area.list
  - iprotector.area.pos1
  - iprotector.area.pos2
  - iprotector.command
  - itemcase.cmd
  - itemcase.destroy
  - massiveeconomy.command.info
  - massiveeconomy.command.money.others
  - massiveeconomy.command.reload
  - massiveeconomy.command.setmoney
  - mw.cmds
  - pocketguard.spg
  - pocketmine.broadcast
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.reload
  - pocketmine.command.teleport
  - pocketmine.command.time
  - simpleauth.chat
  - simpleauth.lastip
  - simpleauthhelper.command.resetpwd
  - simplewarp.command.addwarp
  - simplewarp.command.delwarp
  - simplewarp.command.list.visual
  - simplewarp.command.list.xyz
  - simplewarp.command.warp.other
  - simplewarp.warp
  - wp.cmd.addrm
  - wp.cmd.banitem
  - wp.cmd.gm.exempt
  - wp.cmd.info
  - wp.cmd.noexplode
  - wp.cmd.pvp
  worlds: []
Owner:
  inheritance:
  - User
  - VIP
  - Mod
  - Pluginner
  - Builder
  - Admin
  - YouTuber
  permissions:
  - broadcaster
  - massiveeconomy.*
  - mspawns.*
  - mspawns.info
  - mspawns.reload
  - mspawns.setalias
  - mspawns.sethub
  - mspawns.setspawn
  - mtp.cmd.mtp
  - mtp.destroy
  - pocketguard
  - pocketguard.op
  - pocketmine.command
  - pocketmine.command.ban
  - pocketmine.command.gamemode
  - pocketmine.command.unban
  - pocketmine.command.whitelist
  - pperms.command
  - pperms.command.ppinfo
  - simpleauth.lastip
  - simplewarp
  - simplewarp.command.closewarp
  - simplewarp.command.openwarp
  - simplewarp.warp
  - vanish.other
  - wp.cmd.all
  - wp.cmd.border
  - wp.cmd.gm
  - wp.cmd.gm.exempt
  - wp.cmd.limit
  - wp.cmd.protect
  - wp.cmd.unbreakable

**Comment by AryToNeX** [comment]
---
Utente:
  isDefault: true
  inheritance: []
  permissions:
  - -pocketmine.command.me
  - afk
  - f.command
  - massiveeconomy.command.help
  - massiveeconomy.command.money
  - massiveeconomy.command.pay
  - massiveeconomy.receivedefault
  - mcg76.blockhunt
  - mcg76.plugin.tntrun
  - mspawns.hub
  - mspawns.spawn
  - pchat.colored
  - planb.command.planb
  - pocketguard.command.pg
  - pocketmine.command.list
  - sign
  - sign.command
  - simpleauth.command.login
  - simpleauth.command.register
  - simpleauth.lastip
  - simpleauthhelper.command.chpwd
  - simplehome.home
  - simplehome.sethome
  - simplewarp.command.list
  - simplewarp.command.warp
  - wp.motd
  worlds: []
YouTuber:
  inheritance:
  - Utente
  permissions: []
  worlds: []
VIP:
  inheritance:
  - Utente
  - YouTuber
  permissions:
  - simpleauth.lastip
  worlds: []
Mod:
  inheritance:
  - Utente
  - VIP
  - YouTuber
  permissions:
  - pocketmine.command.ban
  - pocketmine.command.kick
  - pocketmine.command.teleport
  - pocketmine.command.unban
  - simpleauth.lastip
  - vanish
  worlds: []
Pluginner:
  inheritance:
  - Utente
  - VIP
  - Mod
  - YouTuber
  permissions:
  - pocketmine.command.plugins
  - simpleauth.lastip
  worlds: []
Builder:
  inheritance:
  - Utente
  - VIP
  - Mod
  - YouTuber
  permissions:
  - iprotector
  - iprotector.access
  - iprotector.area
  - iprotector.area.create
  - iprotector.area.delete
  - iprotector.area.flag
  - iprotector.area.list
  - iprotector.area.pos1
  - iprotector.area.pos2
  - iprotector.command
  - pocketmine.command.gamemode
  - simpleauth.lastip
  - wp.cmd.gm.exempt
  - wp.cmd.protect.auth
  worlds: []
Admin:
  inheritance:
  - Utente
  - VIP
  - Mod
  - Builder
  - Pluginner
  - YouTuber
  permissions:
  - broadcaster.info
  - broadcaster.reload
  - broadcaster.sendmessage
  - broadcaster.sendpopup
  - iprotector
  - iprotector.access
  - iprotector.area
  - iprotector.area.create
  - iprotector.area.delete
  - iprotector.area.flag
  - iprotector.area.list
  - iprotector.area.pos1
  - iprotector.area.pos2
  - iprotector.command
  - itemcase.cmd
  - itemcase.destroy
  - massiveeconomy.command.info
  - massiveeconomy.command.money.others
  - massiveeconomy.command.reload
  - massiveeconomy.command.setmoney
  - mw.cmds
  - pocketguard.spg
  - pocketmine.broadcast
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.reload
  - pocketmine.command.teleport
  - pocketmine.command.time
  - simpleauth.chat
  - simpleauth.lastip
  - simpleauthhelper.command.resetpwd
  - simplewarp.command.addwarp
  - simplewarp.command.delwarp
  - simplewarp.command.list.visual
  - simplewarp.command.list.xyz
  - simplewarp.command.warp.other
  - simplewarp.warp
  - wp.cmd.addrm
  - wp.cmd.banitem
  - wp.cmd.gm.exempt
  - wp.cmd.info
  - wp.cmd.noexplode
  - wp.cmd.pvp
  worlds: []
Owner:
  inheritance:
  - Utente
  - VIP
  - Mod
  - Pluginner
  - Builder
  - Admin
  - YouTuber
  permissions:
  - broadcaster
  - massiveeconomy.*
  - mspawns.*
  - mspawns.info
  - mspawns.reload
  - mspawns.setalias
  - mspawns.sethub
  - mspawns.setspawn
  - mtp.cmd.mtp
  - mtp.destroy
  - pocketguard
  - pocketguard.op
  - pocketmine.command
  - pocketmine.command.ban
  - pocketmine.command.gamemode
  - pocketmine.command.unban
  - pocketmine.command.whitelist
  - pperms.command
  - pperms.command.ppinfo
  - simpleauth.lastip
  - simplewarp
  - simplewarp.command.closewarp
  - simplewarp.command.openwarp
  - simplewarp.warp
  - vanish.other
  - wp.cmd.all
  - wp.cmd.border
  - wp.cmd.gm
  - wp.cmd.gm.exempt
  - wp.cmd.limit
  - wp.cmd.protect
  - wp.cmd.unbreakable

**Comment by AryToNeX** [comment]
It still doesn't work; and if I do §e{display_name}: §f{message} in the config and this group doesn't have "pchat.colored" permission, in chat there isn't yellow color but is all white.
