### ISSUE TITLE
[Feature Request] Add API for Nickname-Plugins

### ISSUE THREAD

**Issue by Akuroma** [PurePlugins/PureChat#73]
Most of the existing Nick-Plugins don't change the rank prefix.
For example: Player 1 | Rank YouTuber uses /nick.
Because of PureChat, the prefix stays in front of the nickname.
Would it be possible to use a PureChat-API for changing the prefix to Guest or any other prefixes you want, when using the /nick command? Otherwise the Nickname changes, but the rank prefix stays. For example, Nick-Plugins could hide YouTubers during their records or anything else from the other players using a fake prefix and a randomly generated nickname.
Hope you could add this API or code a Nick-Plugin which is compatible with PurePerms/PureChat ;)

**Comment by jasonwynn10** [comment]
`/nick` is not apart of this plugin; therefore, it is not the responsibility of this plugin to deal with another plugin's shortcomings. Talk to the developer of your other plugin if you want it to be made compatible with PureChat.
