### ISSUE TITLE
The Current compiled phar for purechat not working

### ISSUE THREAD

**Issue by jbreadtoasted** [PurePlugins/PureChat#75]
Just letting you know the compiled phar is not working upon server load.

**Comment by jasonwynn10** [comment]
Which phar are you talking about? There are multiple, posted in multiple places

**Comment by jbreadtoasted** [comment]
The latest one that is supposed to support 3.0.0-ALPHA9
[Server] Server thread/ERROR Could not load plugin 'PureChat': Incompatible API version (plugin requires one of: 3.0.0-ALPHA7 3.0.0-ALPHA8 3.0.0-ALPHA9)

**Comment by jbreadtoasted** [comment]
I am using Alpha9 all other plugins i have are loading just fine with dependency of alpha9 but yours is not

**Comment by jbreadtoasted** [comment]
Well the latest compiled phar thats on your code section here dosnt load at all

**Comment by jbreadtoasted** [comment]
Also one last question i was trying to put in a request for a plugin on pmmp.io and it says i have insufficient permissions to post and it says i need to be confirmed. I have ocnfirmed my email so idk. :P

**Comment by jasonwynn10** [comment]
But where are you getting the phar from?

**Comment by jbreadtoasted** [comment]
on your main page under the gihub stuff
https://github.com/PurePlugins/PureChat
And well i understand that but like i said before that current phar on the download section is not working.

**Comment by jasonwynn10** [comment]
Please use Poggit for phars. https://poggit.pmmp.io/p/PureChat/1.4.10-3
