### ISSUE TITLE
Faction plugin

### ISSUE THREAD

**Issue by Antisa14200** [PurePlugins/PureChat#79]
Hi
Does PureChat even supports https://poggit.pmmp.io/p/FactionsPro/1.3.11-7 FactionsPro plugin because everytime I load it, PureChat still says "No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support." 
Cant even make it show in chat tho too.
But factionspro plugin works

**Comment by jasonwynn10** [comment]
You're asking on the wrong repository. Try asking here: https://github.com/poggit-orphanage/PureChat
