### ISSUE TITLE
Code Suggestion for no faction message

### ISSUE THREAD

**Issue by qwefqwfqwefqwef** [PurePlugins/PureChat#8]
if($this->factionsPro != null) 
        {
            if(!$this->factionsPro->isInFaction($player->getName()))
            {
                $chatFormat = str_replace("{faction}", "...", $chatFormat);
            }

May be better to remove the "..."? Looks a lot better. Sorry, i translate in google 

        if($this->factionsPro != null) 
        {
            if(!$this->factionsPro->isInFaction($player->getName()))
            {
                $chatFormat = str_replace("{faction}", "", $chatFormat);
            }
------------------------------------------------------------------------------------------------------------------------------

        if($this->factionsPro != null) 
        {
            if(!$this->factionsPro->isInFaction($player->getName()))
            {            
                $nameTag = str_replace("{faction}", "...", $nameTag);
            }

Replace

        if($this->factionsPro != null) 
        {
            if(!$this->factionsPro->isInFaction($player->getName()))
            {            
                $nameTag = str_replace("{faction}", "", $nameTag);
            }

**Comment by 64FF00** [comment]
I'll add a config option for this instead
